/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kkamath' at '2/23/14 8:49 AM' with Gradle 1.11
 *
 * @author kkamath, @date 2/23/14 8:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
